name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Shadcn UI
      run: |
        npx shadcn-ui@latest init -y
        npx shadcn-ui@latest add card
        npx shadcn-ui@latest add button
        npx shadcn-ui@latest add input
        npx shadcn-ui@latest add alert
      
    - name: Build project
      run: npm run build