name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install @radix-ui/react-alert-dialog
        npm install clsx tailwind-merge
      
    - name: Build project
      run: npm run build

    - name: Cache build
      if: success()
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
          node_modules
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
